Feat mobile screen sup
TransbankDevelopers/transbank-sdk-nodejs-example pull request #43
Opened 2024-11-06 22:58 UTC by victormendoza96

![image](https://github.com/user-attachments/assets/7fcb9ddc-e0c7-44ec-965a-c94f9298a1a1)

2024-11-06 23:00 UTC, mvarlic approved these changes
LGTM!

2024-11-07 15:12 UTC, mastudillot commented
Add shadow to differentiate the menu with the background

<img width="497" alt="image" src="https://github.com/user-attachments/assets/d62df4a1-098f-41fa-bcc0-cbf6398f77d0">

2024-11-07 15:13 UTC, mastudillot requested changes
Add shadow to differentiate the menu with the background

<img width="497" alt="image" src="https://github.com/user-attachments/assets/d62df4a1-098f-41fa-bcc0-cbf6398f77d0">

2024-11-07 20:52 UTC, mastudillot approved these changes
LGTM

2024-11-11 16:22 UTC, merged